// One place for icons. Lucide outline icons (1.5–2px stroke) per the design
// system; four carry fixed meaning everywhere: camera = photo, map pin =
// location, shield = fraud review, truck = collection.

export {
  LuArrowLeft as ArrowLeft,
  LuArrowRight as ArrowRight,
  LuArrowUpDown as SortIcon,
  LuBan as Ban,
  LuCalendar as Calendar,
  LuCamera as Camera,
  LuCheck as Check,
  LuChevronDown as ChevronDown,
  LuChevronLeft as ChevronLeft,
  LuChevronRight as ChevronRight,
  LuCircleAlert as AlertCircle,
  LuCircleCheck as CheckCircle,
  LuCirclePlus as PlusCircle,
  LuClock as Clock,
  LuCopy as Copy,
  LuDownload as Download,
  LuCrosshair as Crosshair,
  LuEllipsis as Ellipsis,
  LuExternalLink as ExternalLink,
  LuEye as Eye,
  LuEyeOff as EyeOff,
  LuFileText as FileText,
  LuFlag as Flag,
  LuGlobe as Globe,
  LuHeadphones as Headphones,
  LuHouse as House,
  LuImage as ImageIcon,
  LuImageOff as ImageOff,
  LuLeaf as Leaf,
  LuListFilter as FilterIcon,
  LuLoaderCircle as Loader,
  LuLocateFixed as LocateFixed,
  LuLock as Lock,
  LuLogIn as LogIn,
  LuLogOut as LogOut,
  LuMail as Mail,
  LuMap as MapIcon,
  LuMapPin as MapPin,
  LuMenu as Menu,
  LuMessageCircleMore as MessageDots,
  LuMessageSquareText as MessageText,
  LuPhone as Phone,
  LuPlay as Play,
  LuQuote as Quote,
  LuRecycle as Recycle,
  LuRefreshCw as Refresh,
  LuRotateCw as Retry,
  LuSearch as Search,
  LuShare as Share,
  LuShieldAlert as ShieldAlert,
  LuShieldCheck as ShieldCheck,
  LuSmartphone as Smartphone,
  LuStar as Star,
  LuTag as Tag,
  LuTrash2 as Trash,
  LuTriangleAlert as Warning,
  LuTruck as Truck,
  LuUpload as Upload,
  LuUser as User,
  LuUserPlus as UserPlus,
  LuUserRound as UserRound,
  LuUserX as UserX,
  LuUsers as Users,
  LuWifiOff as WifiOff,
  LuX as Close,
  LuZap as Zap,
  LuCalendarDays as CalendarDays,
  LuClipboardList as ClipboardList,
} from "react-icons/lu";

export { FaFacebookF as Facebook, FaInstagram as Instagram, FaXTwitter as XTwitter, FaYoutube as Youtube } from "react-icons/fa6";
export { FcGoogle as GoogleLogo } from "react-icons/fc";
