// English strings. French (fr.ts) must have exactly the same keys; the type
// below makes a missing French string a compile error.

export const en = {
  // ---- brand, navigation ----------------------------------------------------
  "brand.sub": "Waste Solutions",
  "brand.tagline": "Clean Cities. Healthy Communities.",
  "nav.home": "Home",
  "nav.services": "Services",
  "nav.reportGuide": "Report Guide",
  "nav.about": "About Us",
  "nav.contact": "Contact",
  "nav.signIn": "Sign in",
  "nav.myAccount": "My account",
  "nav.submitReport": "Submit a Report",
  "nav.menu": "Menu",
  "nav.main": "Main",
  "nav.workspace": "Workspace",
  "nav.councilWorkspace": "Council Workspace",
  "nav.reports": "Reports",
  "nav.employees": "Employees",
  "nav.flaggedCitizens": "Flagged citizens",
  "nav.staff": "Staff",
  "nav.admin": "Admin",
  "tab.label": "Main",
  "tab.home": "Home",
  "tab.report": "Report",
  "tab.myReports": "My reports",
  "tab.profile": "Profile",
  "footer.quickLinks": "Quick Links",
  "footer.ourServices": "Our Services",
  "footer.getInTouch": "Get In Touch",
  "footer.rights": "All rights reserved.",

  // ---- common -----------------------------------------------------------------
  "common.back": "Back",
  "common.backHome": "Back to home",
  "common.breadcrumb": "Breadcrumb",
  "common.cancel": "Cancel",
  "common.close": "Close",
  "common.comingSoon": "Coming soon",
  "common.copied": "Copied",
  "common.copy": "Copy",
  "common.dismiss": "Dismiss",
  "common.error": "Something went wrong. Please try again.",
  "common.loadMore": "Load more",
  "common.next": "Next page",
  "common.open": "Open",
  "common.or": "or",
  "common.previous": "Previous page",
  "common.remove": "Remove",
  "common.retry": "Try again",
  "common.signOut": "Sign out",
  "common.tryAgain": "Try again",
  "notFound.title": "Page not found",
  "notFound.body": "The page you were looking for does not exist or has moved.",
  "errorPage.title": "Something went wrong",
  "errorPage.body": "This page could not be loaded. Check your connection and try again.",

  // ---- status, categories, flags ---------------------------------------------
  "status.PENDING": "Pending",
  "status.IN_PROGRESS": "In Progress",
  "status.DONE": "Done",
  "status.FLAGGED": "Flagged",
  "category.ILLEGAL_DUMPING": "Illegal dumping",
  "category.OVERFLOWING_BIN": "Overflowing bin",
  "category.BLOCKED_DRAIN": "Blocked gutter",
  "category.BURNING_WASTE": "Burning waste",
  "category.HOUSEHOLD_WASTE": "Household waste",
  "category.OTHER": "Waste pile",
  "flag.reason.NOT_WASTE": "Not waste",
  "flag.reason.DUPLICATE": "Duplicate",
  "flag.reason.WRONG_LOCATION": "Wrong location",
  "flag.reason.STAGED": "Staged for the photo",
  "flag.reason.ALREADY_COLLECTED": "Already collected",
  "flag.reason.OTHER": "Other",

  // ---- fields -----------------------------------------------------------------
  "field.phone": "Phone number",
  "field.phoneTitle": "Phone number",
  "field.password": "Password",
  "field.newPassword": "New password",
  "field.confirmPassword": "Confirm password",
  "field.showPassword": "Show password",
  "field.hidePassword": "Hide password",
  "field.username": "Username",
  "field.email": "Email",
  "field.emailTitle": "Email",
  "field.emailOptional": "Email (optional)",
  "field.language": "Language",
  "field.languageTitle": "Language",
  "field.quarter": "Quarter",
  "field.quarterPlain": "Quarter",
  "field.city": "City",
  "password.rules": "Password rules",
  "password.rule.length": "8+ characters",
  "password.rule.number": "A number",
  "password.rule.capital": "A capital letter",
  "password.rule.symbol": "A symbol, like ! - # or @",
  "password.rule.lower": "A lower-case letter",
  "password.rule.match": "Passwords match",
  "password.met": "done",
  "password.notMet": "not yet",

  // ---- auth errors ------------------------------------------------------------
  "auth.error.WRONG_CREDENTIALS": "Those sign-in details do not match. Check them and try again.",
  "auth.error.NOT_CONFIRMED": "Your number is not confirmed yet. We have sent you a new code.",
  "auth.error.ACCOUNT_SUSPENDED": "This account has been suspended.",
  "auth.error.PHONE_TAKEN": "An account with this phone number already exists. Sign in instead.",
  "auth.error.EMAIL_TAKEN": "An account with this email already exists.",
  "auth.error.WEAK_PASSWORD": "Choose a password that meets every rule below.",
  "auth.error.WRONG_CODE": "That code is not right. Check the SMS and enter all 6 digits.",
  "auth.error.CODE_EXPIRED": "That code has expired. Ask for a new one.",
  "auth.error.TOO_MANY_ATTEMPTS": "Too many attempts. Wait a few minutes and try again.",
  "auth.error.INVALID_PHONE": "Enter a Cameroonian number: 9 digits starting with 6 or 2.",
  "auth.error.INVALID_USERNAME": "Use 2 to 30 letters, numbers, dots, dashes or underscores.",
  "auth.error.USERNAME_REQUIRED": "Choose a username.",
  "auth.error.INVALID_EMAIL": "Enter a valid email address.",
  "auth.error.SESSION_EXPIRED": "This step has expired. Please start again.",
  "auth.error.SMS_UNAVAILABLE": "We could not send an SMS right now. Try again in a few minutes.",
  "auth.error.NETWORK": "No connection. Check your network and try again.",
  "auth.error.SERVICE_ERROR": "Something went wrong. Please try again.",

  // ---- landing ----------------------------------------------------------------
  "landing.eyebrow": "Report · Track · Resolve",
  "landing.title1": "Keep Your City Clean from",
  "landing.title2": "Waste.",
  "landing.lead": "Report waste issues in your community, track progress in real time and help us keep Cameroon clean and healthy.",
  "landing.cta": "Submit My Report",
  "landing.ourServices": "Our Services",
  "landing.pill.free": "Free to Use",
  "landing.pill.verified": "Verified Reports",
  "landing.pill.tracking": "Real-Time Tracking",
  "landing.pill.bilingual": "Bilingual FR/EN",
  "landing.heroAlt": "A CLEAN-AM crew member loads rubbish bags from a street bin into a collection truck",
  "landing.stat.label": "Live figures",
  "landing.stat.reports": "Reports submitted",
  "landing.stat.resolved": "Reports resolved",
  "landing.stat.rate": "Resolution rate",
  "landing.stat.inProgress": "Being collected now",
  "landing.why": "Why choose us",
  "landing.servicesTitle1": "One Platform,",
  "landing.servicesTitle2": "Total Waste Coverage.",
  "landing.servicesLead": "Everything you need for a cleaner, healthier and more beautiful Cameroon. Simple, reliable and built for your community.",
  "landing.commitment": "Our commitment",
  "landing.commitTitle1": "A Cleaner Cameroon",
  "landing.commitTitle2": "for a Brighter Tomorrow.",
  "landing.commitBody": "We are committed to cleaner cities, healthier communities and a greener Cameroon. Together, we can reduce waste, protect our environment and build a better future.",
  "landing.commitAlt": "A mother and her son walk along a clean, tree-lined street",
  "landing.trust": "Free for every citizen",
  "landing.join": "Create a free account",
  "service.reporting.title": "Waste Reporting",
  "service.reporting.body": "Report illegal dumps, overflowing bins and other waste issues.",
  "service.reporting.bodyShort": "Report uncollected rubbish with a photo and map pin.",
  "service.tracking.title": "Report Tracking",
  "service.tracking.body": "Track the status of your reports from Pending to Done.",
  "service.fraud.title": "Fraud Protection",
  "service.fraud.body": "Council crews review reports to keep them accurate and genuine.",
  "service.recycling.title": "Recycling Requests",
  "service.recycling.body": "Request recycling collection for plastic, paper and more.",
  "service.pickup.title": "On-Demand Pickup",
  "service.pickup.body": "Schedule a bulk waste collection from your location.",
  "service.subscription.title": "Subscription Collection",
  "service.subscription.body": "Regular waste collection for your home or business.",
  "how.title": "How it works",
  "how.lead": "Report waste in 3 simple steps.",
  "how.step1.title": "Take a photo",
  "how.step1.body": "Snap a clear photo of the waste.",
  "how.step2.title": "Drop a pin",
  "how.step2.body": "Let us know where it is.",
  "how.step3.title": "A crew collects it",
  "how.step3.body": "Our team will clean it up.",

  // ---- home -------------------------------------------------------------------
  "home.title1": "See waste?",
  "home.title2": "Report it.",
  "home.noAccount": "No account needed.",
  "home.hello": "Hello, {name}.",
  "home.cta": "Report waste now",
  "home.guestAs": "You're reporting as",
  "home.guestNew": "You can report without an account.",
  "home.guestNoTracking": "Guests can't follow a report's progress.",
  "home.createAccount": "Create an account",
  "home.toTrack": "to track your reports.",
  "home.latest": "Your latest report",
  "home.seeAll": "See all",
  "home.stat.reports": "Reports",
  "home.stat.collected": "Collected",
  "home.stat.inProgress": "In progress",
  "home.servicesTitle": "Our services",
  "home.servicesLead": "More ways to help keep Buea clean.",

  // ---- sign in / register -----------------------------------------------------
  "login.heroLine": "Every report is a street someone stops walking past.",
  "login.title": "Sign in",
  "login.welcome": "Welcome back.",
  "login.staffWelcome": "Council staff sign in with their work email.",
  "login.forgot": "Forgot your password?",
  "login.submit": "Sign in",
  "login.sendCode": "Send me a code",
  "login.codeHelp": "We'll text a 6-digit code to this number. No password needed.",
  "login.useCode": "Sign in with a code instead",
  "login.usePassword": "Sign in with my password",
  "login.newHere": "New here?",
  "login.createAccount": "Create an account",
  "login.staffSwitch": "Council staff? Sign in with email",
  "login.citizenSwitch": "Citizen? Sign in with your phone number",
  "login.confirmed": "Your number is confirmed. Sign in to continue.",
  "login.resetDone": "Your password has been changed. Sign in with the new one.",
  "register.heroTitle": "Join CLEAN-AM",
  "register.heroSub": "Report waste and follow it until it's collected.",
  "register.title": "Create your account",
  "register.usernameHelp": "Shown to crews on every report you send.",
  "register.emailHelp": "Add it to get status updates by email.",
  "register.submit": "Create account",
  "register.haveAccount": "Already have an account?",
  "register.smsNote": "We'll send a 6-digit code by SMS to confirm your number.",
  "register.guestMove": "Reports you sent from this phone as {label} will move into your new account.",
  "verify.title": "Enter the code we sent",
  "verify.sentTo": "Sent by SMS to {destination}",
  "verify.codeLabel": "6-digit code",
  "verify.submit": "Verify",
  "verify.resendIn": "Didn't get it? Resend code in {time}",
  "verify.didntGet": "Didn't get it?",
  "verify.resend": "Resend code",
  "verify.resent": "New code sent.",
  "verify.changeNumber": "Change number",
  "verify.expiredTitle": "This step has expired",
  "verify.expiredBody": "For your security, codes only work for a short time. Start again to get a new one.",
  "verify.startAgain": "Start again",
  "forgot.title": "Reset your password",
  "forgot.body": "Enter the phone number on your account. We'll text you a code.",
  "forgot.submit": "Send code",
  "forgot.enterCode": "Enter the code",
  "forgot.back": "Back to sign in",
  "forgot.sent": "Code sent to {destination}.",
  "forgot.expires": "It expires in 10 minutes.",
  "reset.title": "Choose a new password",
  "reset.body": "Enter the code we sent and choose a new password for your account.",
  "reset.bodyTo": "Enter the code we sent to {destination} and choose a new password.",
  "reset.code": "SMS code",
  "reset.submit": "Save password",
  "reset.requestCode": "Need a code? Request one",
  "first.title": "Welcome to the CLEAN-AM workspace",
  "first.body": "You signed in with a temporary password. Set your own to continue.",
  "first.signedInAs": "Signed in as",
  "first.submit": "Set password and continue",
  "first.expired": "Sign in again with the temporary password from your invitation email.",

  // ---- submit report ----------------------------------------------------------
  "submit.title": "Report waste",
  "submit.guestAs": "Reporting as {label}. Guests can't follow progress.",
  "submit.guestNew": "Reporting without an account. Guests can't follow progress.",
  "submit.offline": "You're offline. Everything you enter stays here; send it when you're back online.",
  "submit.photo.title": "Photo",
  "submit.photo.sub": "Take a clear photo of the waste.",
  "submit.photo.alt": "Your photo of the waste",
  "submit.takePhoto": "Take a photo",
  "submit.photoHint": "Or choose one from your gallery",
  "submit.retake": "Retake",
  "submit.photoAdded": "Photo added",
  "submit.photoUnsupported": "This photo can't be used. Try taking it again with your camera.",
  "submit.location.title": "Location",
  "submit.location.sub": "We'll use this to show crews where the waste is.",
  "submit.locating": "Finding you…",
  "submit.locationFound": "Location found",
  "submit.pinPlaced": "Pin placed",
  "submit.locationDenied": "Location is off. Tap the map to drop the pin where the waste is.",
  "submit.locationUnavailable": "We couldn't find your location. Tap the map to drop the pin.",
  "submit.adjustPin": "Drag the pin or tap the map to adjust it.",
  "submit.tapMap": "Tap the map where the waste is.",
  "submit.useMyLocation": "Use my location",
  "submit.details.title": "Details",
  "submit.details.sub": "Confirm the quarter and what kind of waste it is.",
  "submit.chooseQuarter": "Choose…",
  "submit.otherQuarter": "Other quarter",
  "submit.otherQuarterLabel": "Name of the quarter",
  "submit.category": "What is it? (optional)",
  "submit.note.title": "Add a note (optional)",
  "submit.note.sub": "Share any extra details to help the team.",
  "submit.note.placeholder": "e.g. Behind the market, been here 5 days",
  "submit.submit": "Submit report",
  "submit.uploading": "Uploading photo… {percent}%",
  "submit.sending": "Sending report…",
  "submit.kept": "Your photo and details are kept. Nothing is lost.",
  "submit.duplicate.title": "You already reported waste here",
  "submit.duplicate.body": "Report {ref} is still open at this spot ({when}). Is this a separate pile?",
  "submit.duplicate.separate": "Yes, it's a separate pile",
  "submit.duplicate.view": "View the open report",
  "submit.error.photo": "A photo is required to submit a report.",
  "submit.error.location": "A location is required. Tap the map where the waste is.",
  "submit.error.outside": "The location must be within Cameroon.",
  "submit.error.quarter": "Please confirm the quarter for this report.",
  "submit.error.network": "Upload failed. Check your connection and try again.",
  "submit.error.photoMissing": "The photo didn't arrive. Tap Try again to send it once more.",
  "submit.error.rate": "You have submitted several reports recently. Please wait a few minutes.",
  "submit.error.rateGuest": "Guests can send 3 reports an hour. Create an account to send more.",
  "submit.error.useAccount": "Reports from this phone now belong to an account. Sign in to report.",
  "submit.error.generic": "The report could not be sent. Please try again.",

  // ---- submitted --------------------------------------------------------------
  "submitted.title": "Report submitted",
  "submitted.body": "Thank you. Your report is now in the council's queue.",
  "submitted.yourReference": "Your reference",
  "submitted.reference": "Reference",
  "submitted.sentAs": "Sent as",
  "submitted.next": "What happens next",
  "submitted.track": "Track my reports",
  "submitted.another": "Report another",
  "submitted.guestTitle": "Want to know when it's cleaned up?",
  "submitted.guestBody": "Create an account and this report moves into it automatically.",
  "submitted.createAccount": "Create account",
  "submitted.missingTitle": "Nothing to show here",
  "submitted.missingBody": "This page shows a report right after you send it.",
  "next.pending": "The council reviews it.",
  "next.inProgress": "A crew is assigned.",
  "next.done": "Waste collected.",

  // ---- my reports / detail ----------------------------------------------------
  "myReports.title": "My reports",
  "myReports.filter": "Filter by status",
  "myReports.all": "All",
  "myReports.emptyTitle": "No reports yet",
  "myReports.empty": "You haven't reported anything yet. When you do, you can follow it here from Pending to Done.",
  "myReports.emptyFiltered": "No reports with this status.",
  "report.title": "Report",
  "report.ref": "Ref:",
  "report.submittedAgo": "Submitted {when}",
  "report.guestTag": "Guest",
  "report.location": "Location",
  "report.progress": "Progress",
  "report.notFoundTitle": "Report not found",
  "report.notFound": "This report doesn't exist or isn't one of yours.",
  "progress.submitted": "Submitted",
  "progress.inProgressNote": "A collection team has been assigned.",
  "progress.doneNote": "The waste has been collected.",
  "progress.complete": "complete",
  "progress.current": "current",
  "progress.notYet": "not yet",

  // ---- profile ----------------------------------------------------------------
  "profile.title": "Profile",
  "profile.memberSince": "Member since {date}",
  "profile.verified": "Verified",
  "profile.verify": "Verify",
  "profile.addEmail": "Add email",
  "profile.emailHelp": "Get status updates by email. Without one, updates show only in the app.",
  "profile.emailOn": "Status updates are sent to this address.",
  "profile.emailUnverified": "Verify this address to get status updates by email.",
  "profile.emailWhy": "We'll email you when a report changes status. We send a code to confirm it's yours.",
  "profile.sendCode": "Send code",
  "profile.emailSentTo": "Enter the code we sent to {destination}.",
  "profile.emailAdded": "Email confirmed. Status updates will arrive there.",
  "profile.reports": "reports",
  "profile.collected": "collected",
  "profile.languageFailed": "Your language could not be saved. Try again.",

  // ---- suspended --------------------------------------------------------------
  "suspended.title": "Your account is suspended",
  "suspended.body": "Several of your reports were found to be false by council crews, so you can't send new reports right now.",
  "suspended.guestTitle": "Reporting is blocked on this device",
  "suspended.guestBody": "Reports from {label} were found to be false by council crews.",
  "suspended.canDo": "What you can do",
  "suspended.pastVisible": "Your past reports stay on record and crews still handle them.",
  "suspended.mistake": "If you think this is a mistake, contact the council.",
  "suspended.contact": "Contact the council",
  "suspended.orCall": "Or call",
  "suspended.mailSubject": "CLEAN-AM account review",

  // ---- staff ------------------------------------------------------------------
  "staff.allReports": "All reports",
  "staff.total": "{count} total",
  "staff.newestFirst": "Newest first",
  "staff.status": "Status",
  "staff.allQuarters": "All quarters",
  "staff.allStatuses": "All statuses",
  "staff.dateRange": "Date range",
  "staff.date.any": "Any time",
  "staff.date.today": "Today",
  "staff.date.7": "Last 7 days",
  "staff.date.30": "Last 30 days",
  "staff.search": "Search reports",
  "staff.searchPlaceholder": "Search by reference, location or reporter…",
  "staff.searchPlaceholderShort": "Search quarter or reference",
  "staff.clearFilters": "Clear filters",
  "staff.filters": "Filters",
  "staff.applyFilters": "Apply filters",
  "staff.quarterChip": "Quarter: {quarter}",
  "staff.col.photo": "Photo",
  "staff.col.reference": "Reference",
  "staff.col.submittedBy": "Submitted by",
  "staff.col.submitted": "Submitted",
  "staff.sortNewest": "Show newest first",
  "staff.sortOldest": "Show oldest first",
  "staff.showingPage": "Page {page} · {count} reports",
  "staff.empty": "No reports yet.",
  "staff.emptyFiltered": "No reports match these filters.",
  "staff.reportTitle": "Report {id}",
  "staff.notFound": "This report doesn't exist.",
  "staff.submittedBy": "Submitted by",
  "staff.guestSince": "Guest since {date}",
  "staff.flags": "{count} flags",
  "staff.directions": "Get directions",
  "staff.history": "Status history",
  "staff.details": "Report details",
  "staff.coordinates": "Coordinates",
  "staff.type": "Report type",
  "staff.note": "Note from reporter",
  "staff.flagsOnReport": "Flags on this report",
  "staff.markInProgress": "Mark In Progress",
  "staff.markDone": "Mark Done",
  "staff.collected": "Collected",
  "staff.flag": "Flag",
  "staff.flagReport": "Flag this report",
  "staff.alreadyFlagged": "You flagged this",
  "staff.statusChanged": "Report marked {status}.",
  "staff.statusConflict": "Someone else updated this report. Showing the latest status.",
  "history.submittedBy": "Submitted by {name}",
  "history.markedBy": "Marked {status} by {name}",
  "flag.title": "Flag this report",
  "flag.sub": "The reporter gets a flag. At {count} flags an admin reviews their account for suspension.",
  "flag.subGuest": "This guest gets a flag. At {count} flags the device is blocked from reporting.",
  "flag.reason": "Reason",
  "flag.note": "Note",
  "flag.noteHint": "(required for Other)",
  "flag.notePlaceholder": "Add a note (optional)…",
  "flag.chooseReason": "Choose a reason.",
  "flag.noteRequired": "Add a note when the reason is Other.",
  "flag.warnCitizen": "This will be {name}'s flag number {nth}. An admin will be asked to suspend the account.",
  "flag.warnGuest": "This will be {name}'s flag number {nth}. This guest will be blocked from reporting.",
  "flag.submit": "Flag report",
  "flag.done": "Flag recorded.",

  // ---- admin ------------------------------------------------------------------
  "admin.employees": "Employees",
  "admin.employeesSub": "Council staff with access to the report workspace.",
  "admin.createEmployee": "Create employee account",
  "admin.createSub": "They'll get an email with temporary sign-in details.",
  "admin.createSubmit": "Create account",
  "admin.fullName": "Full name",
  "admin.locationHelp": "Where they usually work. It does not limit which reports they can see.",
  "admin.error.name": "Enter the employee's full name.",
  "admin.created": "Login details have been emailed to {email}.",
  "admin.col.name": "Name",
  "admin.col.location": "Location",
  "admin.col.created": "Created",
  "admin.col.action": "Action",
  "admin.col.username": "Username",
  "admin.col.flags": "Flags",
  "admin.col.reports": "Reports",
  "admin.active": "Active",
  "admin.revokedChip": "Revoked",
  "admin.suspendedChip": "Suspended",
  "admin.revoke": "Revoke access",
  "admin.noAction": "No action available",
  "admin.revokeTitle": "Revoke access for {name}?",
  "admin.revokeBody": "They will be signed out and can no longer use the workspace. Their past work stays on record, so the account is deactivated rather than deleted.",
  "admin.revoked": "{name}'s access has been revoked.",
  "admin.showingPage": "Page {page} · {count} employees",
  "admin.noEmployeesTitle": "No employees yet",
  "admin.noEmployees": "No employee accounts yet. Create one to give someone access to the workspace.",
  "admin.flagged": "Flagged citizens",
  "admin.flaggedSub": "Citizens with {count} or more flags, most flagged first.",
  "admin.searchCitizens": "Search username or phone…",
  "admin.noFlagged": "No citizens have reached the flag threshold.",
  "admin.noMatch": "No citizens match your search.",
  "admin.citizenPanel": "Citizen details",
  "admin.selectCitizen": "Select a citizen to see their flag history.",
  "admin.reportsAndFlags": "{reports} reports · {flags} flags",
  "admin.flagHistory": "Flag history",
  "admin.noFlagsYet": "No flags recorded.",
  "admin.flagBy": "by {name} · {date}",
  "admin.suspend": "Suspend account",
  "admin.reinstate": "Reinstate account",
  "admin.suspendTitle": "Suspend {name}?",
  "admin.suspendBody": "They will be signed out and can't send reports until an admin reinstates them. They are told by email if they have one.",
  "admin.belowThreshold": "{name} has {count} flags, below the threshold of {threshold}.",
  "admin.overrideConfirm": "I've reviewed the flags and want to suspend anyway.",
  "admin.reasonOptional": "Reason (optional)",
  "admin.noteOptional": "Note (optional)",
  "admin.reinstateTitle": "Reinstate {name}?",
  "admin.reinstateBody": "They can sign in and report again straight away.",
  "admin.resetFlags": "Also reset their flag count to 0",
  "admin.suspendedToast": "{name} has been suspended.",
  "admin.reinstatedToast": "{name} has been reinstated.",
  // Google sign-in and staff two-step verification
  "nav.security": "Security",
  "login.google": "Continue with Google",
  "login.googleFailed": "Google sign-in didn't work. Try again, or sign in with your phone number.",
  "verify.mfaTitle": "Enter your authenticator code",
  "verify.mfaBody": "Open your authenticator app and type the 6-digit code it shows for CLEAN-AM.",
  "verify.mfaHelp": "No access to your authenticator app? Contact your administrator.",
  "security.title": "Sign-in security",
  "security.sub": "Add a second step to your sign-in with an authenticator app such as Google Authenticator or Microsoft Authenticator. It is optional, and recommended for council accounts.",
  "security.statusOn": "Two-step verification is on",
  "security.statusOff": "Two-step verification is off",
  "security.onBody": "After your password, we ask for a code from your authenticator app.",
  "security.offBody": "Only your password protects this account.",
  "security.setUp": "Set up an authenticator app",
  "security.step1": "1. Scan this QR code with your authenticator app.",
  "security.qrAlt": "QR code to add CLEAN-AM to your authenticator app",
  "security.cantScan": "Can't scan it? Type this setup key into the app instead:",
  "security.openApp": "Open in my authenticator app",
  "security.step2": "2. Enter the 6-digit code the app shows.",
  "security.confirm": "Turn on two-step verification",
  "security.turnedOn": "Two-step verification is on.",
  "security.turnOff": "Turn off two-step verification",
  "security.turnOffTitle": "Turn off two-step verification?",
  "security.turnOffBody": "You will sign in with your password only. You can turn it back on at any time.",
  "security.turnedOff": "Two-step verification is off.",
  "security.wrongCode": "That code is not right. Enter the current 6-digit code from your authenticator app.",
  // Installable app and offline page
  "install.title": "Get the CLEAN-AM app",
  "install.body": "Install it on this device: it opens from your home screen like any app. Free, and no app store needed.",
  "install.cta": "Install the app",
  "install.notNow": "Not now",
  "install.share": "Share",
  "install.iosBefore": "On iPhone or iPad, tap",
  "install.iosAfter": "then “Add to Home Screen”.",
  "install.iosHint": "In Safari, tap Share, then “Add to Home Screen”.",
  "offline.title": "You're offline",
  "offline.body": "CLEAN-AM needs a connection to load and send reports. Check your mobile data or Wi-Fi, then try again.",
  // Staff password reset, deactivated staff, rejected input
  "auth.error.INVALID_INPUT": "Some details were not accepted. Check them and try again.",
  "auth.error.ACCOUNT_DISABLED": "This staff account has been deactivated. Contact your administrator.",
  "forgot.bodyStaff": "Enter your work email. We'll email you a code.",
} as const;

export type MessageKey = keyof typeof en;
