// Textes français. « Signalement » pour un signalement de déchets (jamais
// « rapport »), « quartier » tel quel, et le vouvoiement : c'est un service
// municipal.

import type { MessageKey } from "./en";

export const fr: Record<MessageKey, string> = {
  // ---- marque, navigation -----------------------------------------------------
  "brand.sub": "Solutions Déchets",
  "brand.tagline": "Villes propres. Communautés saines.",
  "nav.home": "Accueil",
  "nav.services": "Services",
  "nav.reportGuide": "Guide de signalement",
  "nav.about": "À propos",
  "nav.contact": "Contact",
  "nav.signIn": "Se connecter",
  "nav.myAccount": "Mon compte",
  "nav.submitReport": "Soumettre un signalement",
  "nav.menu": "Menu",
  "nav.main": "Principal",
  "nav.workspace": "Espace de travail",
  "nav.councilWorkspace": "Espace de la commune",
  "nav.reports": "Signalements",
  "nav.employees": "Employés",
  "nav.stats": "Statistiques",
  "nav.unassigned": "Non affectés",
  "nav.flaggedCitizens": "Citoyens signalés",
  "nav.staff": "Agent",
  "nav.admin": "Admin",
  "tab.label": "Principal",
  "tab.home": "Accueil",
  "tab.report": "Signaler",
  "tab.myReports": "Mes signalements",
  "tab.profile": "Profil",
  "footer.quickLinks": "Liens rapides",
  "footer.ourServices": "Nos services",
  "footer.getInTouch": "Nous contacter",
  "footer.rights": "Tous droits réservés.",

  // ---- commun -----------------------------------------------------------------
  "common.back": "Retour",
  "common.backHome": "Retour à l'accueil",
  "common.breadcrumb": "Fil d'Ariane",
  "common.cancel": "Annuler",
  "common.close": "Fermer",
  "common.comingSoon": "Bientôt",
  "common.copied": "Copié",
  "common.copy": "Copier",
  "common.dismiss": "Fermer",
  "common.error": "Un problème est survenu. Veuillez réessayer.",
  "common.loadMore": "Voir plus",
  "common.next": "Page suivante",
  "common.open": "Ouvrir",
  "common.or": "ou",
  "common.previous": "Page précédente",
  "common.remove": "Retirer",
  "common.retry": "Réessayer",
  "common.signOut": "Se déconnecter",
  "common.tryAgain": "Réessayer",
  "notFound.title": "Page introuvable",
  "notFound.body": "La page que vous cherchez n'existe pas ou a été déplacée.",
  "errorPage.title": "Un problème est survenu",
  "errorPage.body": "Cette page n'a pas pu être chargée. Vérifiez votre connexion et réessayez.",

  // ---- statuts, catégories, motifs -------------------------------------------
  "status.PENDING": "En attente",
  "status.IN_PROGRESS": "En cours",
  "status.DONE": "Terminé",
  "status.FLAGGED": "Signalé",
  "category.ILLEGAL_DUMPING": "Dépôt sauvage",
  "category.OVERFLOWING_BIN": "Poubelle débordante",
  "category.BLOCKED_DRAIN": "Caniveau bouché",
  "category.BURNING_WASTE": "Déchets brûlés",
  "category.HOUSEHOLD_WASTE": "Déchets ménagers",
  "category.OTHER": "Tas de déchets",
  "flag.reason.NOT_WASTE": "Pas des déchets",
  "flag.reason.DUPLICATE": "Doublon",
  "flag.reason.WRONG_LOCATION": "Mauvaise localisation",
  "flag.reason.STAGED": "Mis en scène pour la photo",
  "flag.reason.ALREADY_COLLECTED": "Déjà collecté",
  "flag.reason.OTHER": "Autre",

  // ---- champs -----------------------------------------------------------------
  "field.phone": "Numéro de téléphone",
  "field.phoneTitle": "Numéro de téléphone",
  "field.password": "Mot de passe",
  "field.newPassword": "Nouveau mot de passe",
  "field.confirmPassword": "Confirmer le mot de passe",
  "field.showPassword": "Afficher le mot de passe",
  "field.hidePassword": "Masquer le mot de passe",
  "field.username": "Nom d'utilisateur",
  "field.email": "E-mail",
  "field.emailTitle": "E-mail",
  "field.emailOptional": "E-mail (facultatif)",
  "field.language": "Langue",
  "field.languageTitle": "Langue",
  "field.quarter": "Quartier",
  "field.quarterPlain": "Quartier",
  "field.city": "Ville",
  "password.rules": "Règles du mot de passe",
  "password.rule.length": "8 caractères ou plus",
  "password.rule.number": "Un chiffre",
  "password.rule.capital": "Une majuscule",
  "password.rule.symbol": "Un symbole, comme ! - # ou @",
  "password.rule.lower": "Une minuscule",
  "password.rule.match": "Les mots de passe correspondent",
  "password.met": "fait",
  "password.notMet": "pas encore",

  // ---- erreurs de connexion ---------------------------------------------------
  "auth.error.WRONG_CREDENTIALS": "Ces identifiants ne correspondent pas. Vérifiez-les et réessayez.",
  "auth.error.NOT_CONFIRMED": "Votre numéro n'est pas encore confirmé. Nous vous avons envoyé un nouveau code.",
  "auth.error.ACCOUNT_SUSPENDED": "Ce compte a été suspendu.",
  "auth.error.PHONE_TAKEN": "Un compte existe déjà avec ce numéro. Connectez-vous plutôt.",
  "auth.error.EMAIL_TAKEN": "Un compte existe déjà avec cet e-mail.",
  "auth.error.WEAK_PASSWORD": "Choisissez un mot de passe qui respecte toutes les règles ci-dessous.",
  "auth.error.WRONG_CODE": "Ce code n'est pas correct. Vérifiez le SMS et saisissez les 6 chiffres.",
  "auth.error.CODE_EXPIRED": "Ce code a expiré. Demandez-en un nouveau.",
  "auth.error.TOO_MANY_ATTEMPTS": "Trop de tentatives. Patientez quelques minutes et réessayez.",
  "auth.error.INVALID_PHONE": "Saisissez un numéro camerounais : 9 chiffres commençant par 6 ou 2.",
  "auth.error.INVALID_USERNAME": "Utilisez 2 à 30 lettres, chiffres, points, tirets ou traits de soulignement.",
  "auth.error.USERNAME_REQUIRED": "Choisissez un nom d'utilisateur.",
  "auth.error.INVALID_EMAIL": "Saisissez une adresse e-mail valide.",
  "auth.error.SESSION_EXPIRED": "Cette étape a expiré. Veuillez recommencer.",
  "auth.error.SMS_UNAVAILABLE": "Impossible d'envoyer un SMS pour le moment. Réessayez dans quelques minutes.",
  "auth.error.NETWORK": "Pas de connexion. Vérifiez votre réseau et réessayez.",
  "auth.error.SERVICE_ERROR": "Un problème est survenu. Veuillez réessayer.",

  // ---- accueil public ---------------------------------------------------------
  "landing.eyebrow": "Signaler · Suivre · Résoudre",
  "landing.title1": "Gardez votre ville propre, sans",
  "landing.title2": "déchets.",
  "landing.lead": "Signalez les déchets dans votre quartier, suivez leur traitement en temps réel et aidez-nous à garder le Cameroun propre et sain.",
  "landing.cta": "Soumettre mon signalement",
  "landing.ourServices": "Nos services",
  "landing.pill.free": "Gratuit",
  "landing.pill.verified": "Signalements vérifiés",
  "landing.pill.tracking": "Suivi en temps réel",
  "landing.pill.bilingual": "Bilingue FR/EN",
  "landing.heroAlt": "Un agent de CLEAN-AM charge des sacs d'ordures d'une poubelle de rue dans un camion de collecte",
  "landing.stat.label": "Chiffres en direct",
  "landing.stat.reports": "Signalements envoyés",
  "landing.stat.resolved": "Signalements résolus",
  "landing.stat.rate": "Taux de résolution",
  "landing.stat.inProgress": "En cours de collecte",
  "landing.why": "Pourquoi nous choisir",
  "landing.servicesTitle1": "Une plateforme,",
  "landing.servicesTitle2": "tous les déchets couverts.",
  "landing.servicesLead": "Tout ce qu'il faut pour un Cameroun plus propre, plus sain et plus beau. Simple, fiable et pensé pour votre communauté.",
  "landing.commitment": "Notre engagement",
  "landing.commitTitle1": "Un Cameroun plus propre",
  "landing.commitTitle2": "pour un avenir meilleur.",
  "landing.commitBody": "Nous nous engageons pour des villes plus propres, des communautés plus saines et un Cameroun plus vert. Ensemble, réduisons les déchets, protégeons notre environnement et construisons un meilleur avenir.",
  "landing.commitAlt": "Une mère et son fils marchent dans une rue propre et arborée",
  "landing.trust": "Gratuit pour tous les citoyens",
  "landing.join": "Créer un compte gratuit",
  "landing.pill.free.body": "Sans frais, sans paperasse, sans attente.",
  "landing.pill.verified.body": "Les équipes municipales vérifient chaque signalement.",
  "landing.pill.tracking.body": "Suivez chaque signalement jusqu'à son traitement.",
  "landing.pill.bilingual.body": "En français ou en anglais, au choix.",
  "landing.network": "Réseau en direct",
  "landing.networkBody": "{count} signalements envoyés par les citoyens du Cameroun à ce jour.",
  "landing.rateNote": "des signalements traités par les équipes municipales",
  "landing.dash.eyebrow": "Tableau_de_bord_en_direct",
  "landing.dash.title": "Chaque signalement, en toute transparence.",
  "landing.dash.note": "Chiffres en direct de tous les signalements envoyés sur CLEAN-AM.",
  "landing.dash.unavailable": "Les chiffres en direct sont indisponibles pour le moment. Revenez bientôt.",
  "landing.dash.overview": "Vue d'ensemble",
  "landing.dash.total": "Signalements envoyés",
  "landing.dash.share": "{percent} % de tous les signalements",
  "landing.dash.pendingBody": "En attente d'une équipe municipale.",
  "landing.dash.progressBody": "Une équipe est en route ou déjà sur place.",
  "landing.dash.doneBody": "Collectés et clôturés par une équipe municipale.",
  "landing.showcase.eyebrow": "Intervention rapide",
  "landing.showcase.title1": "Des rues propres. Une réponse rapide.",
  "landing.showcase.title2": "Un impact mesurable.",
  "landing.showcase.body": "Chaque photo part directement vers l'équipe qui couvre le quartier, et vous la suivez jusqu'à ce que les déchets soient enlevés.",
  "service.reporting.title": "Signalement de déchets",
  "service.reporting.body": "Signalez les dépôts sauvages, les poubelles débordantes et les autres problèmes.",
  "service.reporting.bodyShort": "Signalez les déchets non collectés avec une photo et un repère.",
  "service.tracking.title": "Suivi des signalements",
  "service.tracking.body": "Suivez vos signalements, d'En attente à Terminé.",
  "service.fraud.title": "Lutte contre la fraude",
  "service.fraud.body": "Les équipes de la commune vérifient les signalements pour qu'ils restent fiables.",
  "service.recycling.title": "Demandes de recyclage",
  "service.recycling.body": "Demandez la collecte du plastique, du papier et plus encore.",
  "service.pickup.title": "Collecte à la demande",
  "service.pickup.body": "Programmez l'enlèvement d'encombrants à votre adresse.",
  "service.subscription.title": "Collecte par abonnement",
  "service.subscription.body": "Une collecte régulière pour votre domicile ou votre entreprise.",
  "how.title": "Comment ça marche",
  "how.lead": "Signalez des déchets en 3 étapes simples.",
  "how.step1.title": "Prenez une photo",
  "how.step1.body": "Photographiez clairement les déchets.",
  "how.step2.title": "Placez un repère",
  "how.step2.body": "Indiquez-nous où ils se trouvent.",
  "how.step3.title": "Une équipe collecte",
  "how.step3.body": "Nos agents nettoient.",

  // ---- accueil ---------------------------------------------------------------
  "home.title1": "Des déchets ?",
  "home.title2": "Signalez-les.",
  "home.noAccount": "Sans compte.",
  "home.hello": "Bonjour, {name}.",
  "home.cta": "Signaler maintenant",
  "home.guestAs": "Vous signalez en tant que",
  "home.guestNew": "Vous pouvez signaler sans compte.",
  "home.guestNoTracking": "Les invités ne peuvent pas suivre leurs signalements.",
  "home.createAccount": "Créez un compte",
  "home.toTrack": "pour les suivre.",
  "home.latest": "Votre dernier signalement",
  "home.seeAll": "Tout voir",
  "home.stat.reports": "Signalements",
  "home.stat.collected": "Collectés",
  "home.stat.inProgress": "En cours",
  "home.servicesTitle": "Nos services",
  "home.servicesLead": "D'autres façons de garder Buea propre.",

  // ---- connexion / inscription -----------------------------------------------
  "login.heroLine": "Chaque signalement, c'est une rue qu'on n'évite plus.",
  "login.title": "Connexion",
  "login.welcome": "Bon retour.",
  "login.staffWelcome": "Les agents de la commune se connectent avec leur e-mail professionnel.",
  "login.forgot": "Mot de passe oublié ?",
  "login.submit": "Se connecter",
  "login.sendCode": "Recevoir un code",
  "login.codeHelp": "Nous enverrons un code à 6 chiffres à ce numéro. Pas besoin de mot de passe.",
  "login.useCode": "Se connecter avec un code",
  "login.usePassword": "Se connecter avec mon mot de passe",
  "login.newHere": "Nouveau ?",
  "login.createAccount": "Créer un compte",
  "login.staffSwitch": "Agent de la commune ? Connexion par e-mail",
  "login.citizenSwitch": "Citoyen ? Connexion avec votre numéro",
  "login.confirmed": "Votre numéro est confirmé. Connectez-vous pour continuer.",
  "login.resetDone": "Votre mot de passe a été modifié. Connectez-vous avec le nouveau.",
  "register.heroTitle": "Rejoignez CLEAN-AM",
  "register.heroSub": "Signalez les déchets et suivez-les jusqu'à la collecte.",
  "register.title": "Créer votre compte",
  "register.usernameHelp": "Affiché aux équipes sur chaque signalement que vous envoyez.",
  "register.emailHelp": "Ajoutez-le pour recevoir les mises à jour par e-mail.",
  "register.submit": "Créer le compte",
  "register.haveAccount": "Vous avez déjà un compte ?",
  "register.smsNote": "Nous enverrons un code à 6 chiffres par SMS pour confirmer votre numéro.",
  "register.guestMove": "Les signalements envoyés depuis ce téléphone en tant que {label} seront transférés dans votre nouveau compte.",
  "verify.title": "Saisissez le code reçu",
  "verify.sentTo": "Envoyé par SMS au {destination}",
  "verify.codeLabel": "Code à 6 chiffres",
  "verify.submit": "Vérifier",
  "verify.resendIn": "Pas reçu ? Renvoyer le code dans {time}",
  "verify.didntGet": "Pas reçu ?",
  "verify.resend": "Renvoyer le code",
  "verify.resent": "Nouveau code envoyé.",
  "verify.changeNumber": "Changer de numéro",
  "verify.expiredTitle": "Cette étape a expiré",
  "verify.expiredBody": "Pour votre sécurité, les codes ne sont valables que peu de temps. Recommencez pour en recevoir un nouveau.",
  "verify.startAgain": "Recommencer",
  "forgot.title": "Réinitialiser le mot de passe",
  "forgot.body": "Saisissez le numéro de votre compte. Nous vous enverrons un code par SMS.",
  "forgot.submit": "Envoyer le code",
  "forgot.enterCode": "Saisir le code",
  "forgot.back": "Retour à la connexion",
  "forgot.sent": "Code envoyé au {destination}.",
  "forgot.expires": "Il expire dans 10 minutes.",
  "reset.title": "Choisir un nouveau mot de passe",
  "reset.body": "Saisissez le code reçu et choisissez un nouveau mot de passe.",
  "reset.bodyTo": "Saisissez le code envoyé au {destination} et choisissez un nouveau mot de passe.",
  "reset.code": "Code SMS",
  "reset.submit": "Enregistrer",
  "reset.requestCode": "Besoin d'un code ? Demandez-en un",
  "first.title": "Bienvenue dans l'espace CLEAN-AM",
  "first.body": "Vous vous êtes connecté avec un mot de passe temporaire. Choisissez le vôtre pour continuer.",
  "first.signedInAs": "Connecté en tant que",
  "first.submit": "Définir le mot de passe et continuer",
  "first.expired": "Reconnectez-vous avec le mot de passe temporaire reçu dans votre e-mail d'invitation.",

  // ---- signaler ---------------------------------------------------------------
  "submit.title": "Signaler des déchets",
  "submit.guestAs": "Vous signalez en tant que {label}. Les invités ne peuvent pas suivre leurs signalements.",
  "submit.guestNew": "Vous signalez sans compte. Les invités ne peuvent pas suivre leurs signalements.",
  "submit.offline": "Vous êtes hors ligne. Tout ce que vous saisissez est conservé ; envoyez-le une fois reconnecté.",
  "submit.photo.title": "Photo",
  "submit.photo.sub": "Prenez une photo claire des déchets.",
  "submit.photo.alt": "Votre photo des déchets",
  "submit.takePhoto": "Prendre une photo",
  "submit.photoHint": "Ou choisissez-en une dans votre galerie",
  "submit.retake": "Reprendre",
  "submit.photoAdded": "Photo ajoutée",
  "submit.photoUnsupported": "Cette photo ne peut pas être utilisée. Reprenez-la avec votre appareil photo.",
  "submit.location.title": "Localisation",
  "submit.location.sub": "Elle indique aux équipes où se trouvent les déchets.",
  "submit.locating": "Localisation…",
  "submit.locationFound": "Position trouvée",
  "submit.pinPlaced": "Repère placé",
  "submit.locationDenied": "La localisation est désactivée. Touchez ci-dessous pour l'activer ou choisissez votre quartier.",
  "submit.locationUnavailable": "Position indisponible. Activez le GPS de votre appareil ou choisissez votre quartier ci-dessous.",
  "submit.locationApprox": "Cette position GPS est approximative (±{m} m). Faites glisser le repère à l'endroit exact.",
  "submit.adjustPin": "Faites glisser le repère ou touchez la carte pour l'ajuster.",
  "submit.tapMap": "Touchez la carte à l'endroit des déchets.",
  "submit.useMyLocation": "Ma position",
  "submit.retryLocation": "Activer la localisation / Réessayer",
  "submit.details.title": "Détails",
  "submit.details.sub": "Confirmez le quartier et le type de déchets.",
  "submit.chooseQuarter": "Choisir…",
  "submit.otherQuarter": "Autre quartier",
  "submit.otherQuarterLabel": "Nom du quartier",
  "submit.category": "De quoi s'agit-il ? (facultatif)",
  "submit.note.title": "Ajouter une note (facultatif)",
  "submit.note.sub": "Donnez des détails utiles à l'équipe.",
  "submit.note.placeholder": "ex. Derrière le marché, là depuis 5 jours",
  "submit.submit": "Envoyer le signalement",
  "submit.uploading": "Envoi en cours…",
  "submit.sending": "Envoi du signalement…",
  "submit.kept": "Votre photo et vos informations sont conservées. Rien n'est perdu.",
  "submit.duplicate.title": "Vous avez déjà signalé des déchets ici",
  "submit.duplicate.body": "Le signalement {ref} est encore ouvert à cet endroit ({when}). S'agit-il d'un autre tas ?",
  "submit.duplicate.separate": "Oui, c'est un autre tas",
  "submit.duplicate.view": "Voir le signalement ouvert",
  "submit.error.photo": "Une photo est requise pour soumettre un signalement.",
  "submit.error.location": "Une localisation est requise. Touchez la carte à l'endroit des déchets.",
  "submit.error.outside": "La localisation doit se trouver au Cameroun.",
  "submit.error.quarter": "Veuillez confirmer le quartier de ce signalement.",
  "submit.error.network": "L'envoi a échoué. Vérifiez votre connexion et réessayez.",
  "submit.error.photoMissing": "La photo n'est pas arrivée. Touchez Réessayer pour la renvoyer.",
  "submit.error.rate": "Vous avez soumis plusieurs signalements récemment. Veuillez patienter quelques minutes.",
  "submit.error.rateGuest": "Les invités peuvent envoyer 3 signalements par heure. Créez un compte pour en envoyer plus.",
  "submit.error.useAccount": "Les signalements de ce téléphone appartiennent désormais à un compte. Connectez-vous pour signaler.",
  "submit.error.generic": "Le signalement n'a pas pu être envoyé. Veuillez réessayer.",

  // ---- envoyé -----------------------------------------------------------------
  "submitted.title": "Signalement envoyé",
  "submitted.body": "Merci. Votre signalement est dans la file de la commune.",
  "submitted.sent": "Envoyé",
  "submitted.yourReference": "Votre référence",
  "submitted.reference": "Référence",
  "submitted.sentAs": "Envoyé en tant que",
  "submitted.next": "La suite",
  "submitted.track": "Suivre mes signalements",
  "submitted.another": "Signaler autre chose",
  "submitted.guestTitle": "Vous voulez savoir quand c'est nettoyé ?",
  "submitted.guestBody": "Créez un compte et ce signalement y sera transféré automatiquement.",
  "submitted.createAccount": "Créer un compte",
  "submitted.missingTitle": "Rien à afficher",
  "submitted.missingBody": "Cette page affiche un signalement juste après son envoi.",
  "next.pending": "La commune l'examine.",
  "next.inProgress": "Une équipe est assignée.",
  "next.done": "Déchets collectés.",

  // ---- mes signalements --------------------------------------------------------
  "myReports.title": "Mes signalements",
  "myReports.filter": "Filtrer par statut",
  "myReports.all": "Tous",
  "myReports.emptyTitle": "Aucun signalement",
  "myReports.empty": "Vous n'avez encore rien signalé. Dès que ce sera le cas, vous pourrez suivre votre signalement ici, d'En attente à Terminé.",
  "myReports.emptyFiltered": "Aucun signalement avec ce statut.",
  "report.title": "Signalement",
  "report.ref": "Réf. :",
  "report.submittedAgo": "Envoyé {when}",
  "report.guestTag": "Invité",
  "report.location": "Localisation",
  "report.progress": "Avancement",
  "report.notFoundTitle": "Signalement introuvable",
  "report.notFound": "Ce signalement n'existe pas ou ne vous appartient pas.",
  "progress.submitted": "Envoyé",
  "progress.inProgressNote": "Une équipe de collecte a été assignée.",
  "progress.doneNote": "Les déchets ont été collectés.",
  "progress.complete": "terminé",
  "progress.current": "en cours",
  "progress.notYet": "pas encore",

  // ---- profil -----------------------------------------------------------------
  "profile.title": "Profil",
  "profile.memberSince": "Membre depuis {date}",
  "profile.verified": "Vérifié",
  "profile.verify": "Vérifier",
  "profile.addEmail": "Ajouter un e-mail",
  "profile.wrongEmailCode": "Ce code n'est pas correct. Vérifiez l'e-mail envoyé et saisissez les 6 chiffres.",
  "profile.emailHelp": "Recevez les mises à jour par e-mail. Sans e-mail, elles s'affichent seulement dans l'application.",
  "profile.emailOn": "Les mises à jour sont envoyées à cette adresse.",
  "profile.emailUnverified": "Vérifiez cette adresse pour recevoir les mises à jour par e-mail.",
  "profile.emailWhy": "Nous vous écrirons quand un signalement change de statut. Un code confirme que l'adresse est la vôtre.",
  "profile.sendCode": "Envoyer le code",
  "profile.emailSentTo": "Saisissez le code envoyé à {destination}.",
  "profile.emailAdded": "E-mail confirmé. Les mises à jour y seront envoyées.",
  "profile.reports": "signalements",
  "profile.collected": "collectés",
  "profile.languageFailed": "Votre langue n'a pas pu être enregistrée. Réessayez.",

  // ---- suspendu ---------------------------------------------------------------
  "suspended.title": "Votre compte est suspendu",
  "suspended.body": "Plusieurs de vos signalements ont été jugés faux par les équipes de la commune ; vous ne pouvez donc pas en envoyer de nouveaux pour le moment.",
  "suspended.guestTitle": "Les signalements sont bloqués sur cet appareil",
  "suspended.guestBody": "Des signalements de {label} ont été jugés faux par les équipes de la commune.",
  "suspended.canDo": "Ce que vous pouvez faire",
  "suspended.pastVisible": "Vos signalements passés restent enregistrés et les équipes continuent de les traiter.",
  "suspended.mistake": "Si vous pensez qu'il s'agit d'une erreur, contactez la commune.",
  "suspended.contact": "Contacter la commune",
  "suspended.orCall": "Ou appelez le",
  "suspended.mailSubject": "Réexamen de compte CLEAN-AM",

  // ---- agents -----------------------------------------------------------------
  "staff.allReports": "Tous les signalements",
  "staff.total": "{count} au total",
  "staff.newestFirst": "Les plus récents d'abord",
  "staff.status": "Statut",
  "staff.allQuarters": "Tous les quartiers",
  "staff.allStatuses": "Tous les statuts",
  "staff.dateRange": "Période",
  "staff.date.any": "Toutes dates",
  "staff.date.today": "Aujourd'hui",
  "staff.date.7": "7 derniers jours",
  "staff.date.30": "30 derniers jours",
  "staff.search": "Rechercher des signalements",
  "staff.searchPlaceholder": "Rechercher par référence, lieu ou auteur…",
  "staff.searchPlaceholderShort": "Quartier ou référence",
  "staff.clearFilters": "Effacer les filtres",
  "staff.filters": "Filtres",
  "staff.applyFilters": "Appliquer",
  "staff.quarterChip": "Quartier : {quarter}",
  "staff.col.photo": "Photo",
  "staff.col.reference": "Référence",
  "staff.col.submittedBy": "Soumis par",
  "staff.col.submitted": "Envoyé",
  "staff.sortNewest": "Plus récents d'abord",
  "staff.sortOldest": "Plus anciens d'abord",
  "staff.showingPage": "Page {page} · {count} signalements",
  "staff.empty": "Aucun signalement pour le moment.",
  "staff.emptyFiltered": "Aucun signalement ne correspond à ces filtres.",
  "staff.reportTitle": "Signalement {id}",
  "staff.notFound": "Ce signalement n'existe pas.",
  "staff.submittedBy": "Soumis par",
  "staff.guestSince": "Invité depuis {date}",
  "staff.flags": "{count} signalements",
  "staff.directions": "Itinéraire",
  "staff.history": "Historique des statuts",
  "staff.details": "Détails du signalement",
  "staff.coordinates": "Coordonnées",
  "staff.type": "Type",
  "staff.note": "Note de l'auteur",
  "staff.assignedTo": "Affecté à",
  "staff.unassigned": "Pas encore affecté",
  "staff.notAssignedToYou": "Ce signalement est affecté à une autre équipe ; vous pouvez le consulter mais pas en changer le statut.",
  "staff.flagsOnReport": "Motifs signalés sur ce signalement",
  "staff.markInProgress": "Marquer en cours",
  "staff.markDone": "Marquer terminé",
  "staff.collected": "Collecté",
  "staff.flag": "Signaler",
  "staff.flagReport": "Signaler ce rapport",
  "staff.alreadyFlagged": "Déjà signalé par vous",
  "staff.statusChanged": "Signalement marqué « {status} ».",
  "staff.statusConflict": "Quelqu'un d'autre a mis à jour ce signalement. Voici le dernier statut.",
  "history.submittedBy": "Soumis par {name}",
  "history.markedBy": "Marqué « {status} » par {name}",
  "flag.title": "Signaler ce rapport",
  "flag.sub": "L'auteur reçoit un signalement. À {count}, son compte est suspendu automatiquement ; un admin peut le rétablir.",
  "flag.subGuest": "Cet invité reçoit un signalement. À {count}, l'appareil ne peut plus signaler.",
  "flag.reason": "Motif",
  "flag.note": "Note",
  "flag.noteHint": "(obligatoire pour Autre)",
  "flag.notePlaceholder": "Ajouter une note (facultatif)…",
  "flag.chooseReason": "Choisissez un motif.",
  "flag.noteRequired": "Ajoutez une note quand le motif est Autre.",
  "flag.warnCitizen": "Ce sera le signalement n° {nth} pour {name}. Son compte sera suspendu automatiquement jusqu'à son rétablissement par un admin.",
  "flag.warnGuest": "Ce sera le signalement n° {nth} pour {name}. Cet invité ne pourra plus signaler.",
  "flag.submit": "Signaler",
  "flag.done": "Signalement enregistré.",

  // ---- admin ------------------------------------------------------------------
  "admin.employees": "Employés",
  "admin.employeesSub": "Agents de la commune ayant accès à l'espace des signalements.",
  "admin.createEmployee": "Créer un compte employé",
  "admin.createSub": "Ils recevront un e-mail avec des identifiants temporaires.",
  "admin.createSubmit": "Créer le compte",
  "admin.fullName": "Nom complet",
  "admin.locationHelp": "Lieu de travail habituel. Cela ne limite pas les signalements visibles.",
  "admin.error.name": "Saisissez le nom complet de l'employé.",
  "admin.zones": "Zones de couverture",
  "admin.zonesHelp": "Choisissez les quartiers dont cet employé est responsable. Les nouveaux signalements dans ces quartiers sont affectés automatiquement à l'employé couvrant le plus proche.",
  "admin.zonesSelected": "{count} sélectionné(s) : {zones}",
  "admin.error.zones": "Sélectionnez au moins une zone de couverture.",
  "admin.unassignedTitle": "Signalements non affectés",
  "admin.unassignedSub": "Signalements dans des quartiers qu'aucun employé actif ne couvre. Créez un employé pour ces zones et ils seront pris en charge automatiquement.",
  "admin.unassignedBanner": "{count} signalement(s) en attente car aucun employé ne couvre leur zone.",
  "admin.unassignedNoneTitle": "Tout est couvert",
  "admin.unassignedNone": "Chaque signalement en attente a été affecté à une équipe.",
  "admin.created": "Les identifiants ont été envoyés par e-mail à {email}.",
  "admin.edit": "Modifier",
  "admin.editEmployee": "Modifier le compte employé",
  "admin.editSub": "Modifier les zones de couverture, le nom ou le statut.",
  "admin.editSubmit": "Enregistrer les modifications",
  "admin.updated": "Employé {name} mis à jour.",
  "admin.reactivate": "Réactiver le compte",
  "admin.reactivateHelp": "Rétablir l'accès à l'espace de travail du personnel.",
  "admin.statusLabel": "Statut du compte",
  "admin.accountActive": "Compte actif",
  "admin.accountRevoked": "Compte révoqué / inactif",
  "admin.col.name": "Nom",
  "admin.col.location": "Localisation",
  "admin.col.created": "Créé le",
  "admin.col.action": "Action",
  "admin.col.username": "Nom d'utilisateur",
  "admin.col.flags": "Signalements",
  "admin.col.reports": "Rapports",
  "admin.active": "Actif",
  "admin.revokedChip": "Révoqué",
  "admin.suspendedChip": "Suspendu",
  "admin.revoke": "Révoquer l'accès",
  "admin.noAction": "Aucune action",
  "admin.revokeTitle": "Révoquer l'accès de {name} ?",
  "admin.revokeBody": "La personne sera déconnectée et ne pourra plus utiliser l'espace. Son travail passé reste enregistré : le compte est désactivé, pas supprimé.",
  "admin.revoked": "L'accès de {name} a été révoqué.",
  "admin.showingPage": "Page {page} · {count} employés",
  "admin.noEmployeesTitle": "Aucun employé",
  "admin.noEmployees": "Aucun compte employé pour le moment. Créez-en un pour donner accès à l'espace de travail.",
  "admin.flagged": "Citoyens signalés",
  "admin.flaggedSub": "Citoyens ayant {count} signalements ou plus, les plus signalés d'abord.",
  "admin.searchCitizens": "Rechercher un nom ou un numéro…",
  "admin.noFlagged": "Aucun citoyen n'a atteint le seuil de signalements.",
  "admin.noMatch": "Aucun citoyen ne correspond à votre recherche.",
  "admin.citizenPanel": "Détails du citoyen",
  "admin.selectCitizen": "Sélectionnez un citoyen pour voir son historique.",
  "admin.reportsAndFlags": "{reports} rapports · {flags} signalements",
  "admin.flagHistory": "Historique des signalements",
  "admin.noFlagsYet": "Aucun signalement enregistré.",
  "admin.flagBy": "par {name} · {date}",
  "admin.suspend": "Suspendre le compte",
  "admin.reinstate": "Rétablir le compte",
  "admin.suspendTitle": "Suspendre {name} ?",
  "admin.suspendBody": "La personne sera déconnectée et ne pourra plus signaler jusqu'à son rétablissement par un admin. Elle est prévenue par e-mail si elle en a un.",
  "admin.belowThreshold": "{name} a {count} signalements, sous le seuil de {threshold}.",
  "admin.overrideConfirm": "J'ai examiné les signalements et je veux quand même suspendre.",
  "admin.reasonOptional": "Motif (facultatif)",
  "admin.noteOptional": "Note (facultatif)",
  "admin.reinstateTitle": "Rétablir {name} ?",
  "admin.reinstateBody": "La personne pourra se reconnecter et signaler immédiatement.",
  "admin.resetFlags": "Remettre aussi son compteur de signalements à 0",
  "admin.suspendedToast": "{name} a été suspendu.",
  "admin.reinstatedToast": "{name} a été rétabli.",
  "admin.assignedReports": "Rapports assignés",
  "admin.assignedReportsSub": "Rapports actuellement ou précédemment assignés à {name}.",
  "admin.viewReports": "Voir les rapports",
  "admin.reportsAssigned": "Rapports assignés",
  "admin.noAssignedReports": "Aucun rapport n'a encore été assigné à cet employé.",
  "admin.tabAssigned": "Rapports assignés",
  "admin.tabEdit": "Modifier le compte",
  "admin.workload": "Charge de travail",
  "admin.resolutionRate": "Taux de résolution",
  "admin.allAssigned": "Tous ({count})",
  "admin.pendingCount": "En attente ({count})",
  "admin.inProgressCount": "En cours ({count})",
  "admin.resolvedCount": "Résolus ({count})",
  "admin.statsTitle": "Tableau de statistiques",
  "admin.statsSub": "Analytique d'assainissement : volume de déchets éliminés, vitesse d'arrivée des signalements et délais de résolution.",
  "admin.timeRange.7d": "7 derniers jours",
  "admin.timeRange.30d": "30 derniers jours",
  "admin.timeRange.all": "Tout l'historique",
  "admin.kpi.trashDisposed": "Déchets éliminés",
  "admin.kpi.trashDisposedSub": "Signalements nettoyés et résolus",
  "admin.kpi.intakeRate": "Vitesse d'arrivée",
  "admin.kpi.intakeRateSub": "Signalements citoyens entrants",
  "admin.kpi.turnaround": "Délai moyen de résolution",
  "admin.kpi.turnaroundSub": "De la soumission à la complétion",
  "admin.kpi.activeStaff": "Personnel actif",
  "admin.kpi.activeStaffSub": "Couvrant les zones communales",
  "admin.chart.disposalTitle": "Quantité de déchets éliminés par catégorie",
  "admin.chart.disposalBadge": "Volume de déchets & complétion",
  "admin.chart.disposalExplanationTitle": "Analyse de l'élimination des déchets et volumes traités",
  "admin.chart.intakeTitle": "Taux d'arrivée des signalements & vitesse d'entrée",
  "admin.chart.intakeBadge": "Entrées vs cadence de traitement",
  "admin.chart.intakeExplanationTitle": "Vitesse d'entrée et tendances des signalements citoyens",
  "admin.chart.turnaroundTitle": "Délai de prise en charge et résolution (MTTR & SLA)",
  "admin.chart.turnaroundBadge": "Rapidité d'intervention & tranches SLA",
  "admin.chart.turnaroundExplanationTitle": "Analyse des délais de réponse et rapidité d'intervention",
  "admin.workloadTitle": "Assignations des employés & répartition des états",
  "admin.workloadSub": "Aperçu des signalements assignés au personnel municipal et leurs états actuels.",
  "admin.col.workload": "Charge assignée",
  "admin.col.states": "États des rapports",
  "admin.col.resolved": "Résolu",
  "admin.col.inProgress": "En cours",
  "admin.col.pending": "En attente",
  // Google sign-in and staff two-step verification
  "nav.security": "Sécurité",
  "login.google": "Continuer avec Google",
  "login.googleFailed": "La connexion avec Google n'a pas abouti. Réessayez ou connectez-vous avec votre numéro de téléphone.",
  "verify.mfaTitle": "Saisissez le code de votre application",
  "verify.mfaBody": "Ouvrez votre application d'authentification et saisissez le code à 6 chiffres affiché pour CLEAN-AM.",
  "verify.mfaHelp": "Plus d'accès à votre application d'authentification ? Contactez votre administrateur.",
  "security.title": "Sécurité de connexion",
  "security.sub": "Ajoutez une deuxième étape à votre connexion avec une application d'authentification comme Google Authenticator ou Microsoft Authenticator. C'est facultatif, et recommandé pour les comptes de la mairie.",
  "security.statusOn": "La validation en deux étapes est activée",
  "security.statusOff": "La validation en deux étapes est désactivée",
  "security.onBody": "Après votre mot de passe, nous demandons un code de votre application d'authentification.",
  "security.offBody": "Seul votre mot de passe protège ce compte.",
  "security.setUp": "Configurer la validation",
  "security.step1": "1. Scannez ce code QR avec votre application d'authentification.",
  "security.qrAlt": "Code QR pour ajouter CLEAN-AM à votre application d'authentification",
  "security.cantScan": "Impossible de scanner ? Saisissez plutôt cette clé dans l'application :",
  "security.openApp": "Ouvrir dans mon application d'authentification",
  "security.step2": "2. Saisissez le code à 6 chiffres affiché par l'application.",
  "security.confirm": "Activer la validation en deux étapes",
  "security.turnedOn": "La validation en deux étapes est activée.",
  "security.turnOff": "Désactiver la validation en deux étapes",
  "security.turnOffTitle": "Désactiver la validation en deux étapes ?",
  "security.turnOffBody": "Vous vous connecterez avec votre mot de passe seulement. Vous pourrez la réactiver à tout moment.",
  "security.turnedOff": "La validation en deux étapes est désactivée.",
  "security.wrongCode": "Ce code n'est pas correct. Saisissez le code à 6 chiffres affiché en ce moment dans votre application.",
  // Installable app and offline page
  "install.title": "Installez l'application CLEAN-AM",
  "install.body": "Installez-la sur cet appareil : elle s'ouvre depuis l'écran d'accueil comme une application. Gratuit, sans passer par un store.",
  "install.cta": "Installer l'application",
  "install.notNow": "Plus tard",
  "install.share": "Partager",
  "install.iosBefore": "Sur iPhone ou iPad, touchez",
  "install.iosAfter": "puis « Sur l'écran d'accueil ».",
  "install.iosHint": "Dans Safari, touchez Partager, puis « Sur l'écran d'accueil ».",
  "offline.title": "Vous êtes hors ligne",
  "offline.body": "CLEAN-AM a besoin d'une connexion pour charger et envoyer les signalements. Vérifiez vos données mobiles ou le Wi-Fi, puis réessayez.",
  // Staff password reset, deactivated staff, rejected input
  "auth.error.INVALID_INPUT": "Certaines informations n'ont pas été acceptées. Vérifiez-les et réessayez.",
  "auth.error.ACCOUNT_DISABLED": "Ce compte du personnel a été désactivé. Contactez votre administrateur.",
  "forgot.bodyStaff": "Saisissez votre e-mail professionnel. Nous vous enverrons un code par e-mail.",
};
